/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import * as React from 'react';
import AndroidDocumentPicker from 'react-native-android-document-picker';
import { useEffect, useState } from 'react';
import { StyleSheet, View, Text, Image, ScrollView } from 'react-native';

export default function App() {

  const [files, setFiles] = useState([]);

  useEffect(() => {
    console.log('files', files);
  }, [files])
  
  return (
    <View style={styles.container}>
      <ScrollView>
      <Text onPress={async () => {

        let newFiles = [...files];

        await AndroidDocumentPicker.openDocument({multipleFiles: true, fileTypes: ["image/*", "application/pdf"]}, (array) => {
          console.log('array', array);
          array.forEach((el) => {
            const doc = JSON.parse(el);
          
            console.log("doc:", doc);
            // {"fileName": "some_pdf_file.pdf", 
            // "fileSize": "450110", 
            // "fileType": "application/pdf", 
            // "fileUri": "content://com.android.providers.downloads.documents/document/1058"}
            
            newFiles.push({
            fileName: doc.fileName,
            uri: doc.fileUri,
            type: doc.fileType,
            size: doc.fileSize
            });
          });

          setFiles(newFiles);
        }, 
        (error) => {
          console.log('error', error);
        });
      }}>Press</Text>

      <View>
        {files.map((file) => 
          <View key={file.fileName}>
          <Text>{file.fileName}</Text>
          <Image source={{uri: file.uri}}
          key={file}
          style={{
            borderColor: 'black',
            borderWidth: 2,
            borderRadius: 5,
            width: 100,
            height: 100,
            margin: 5,
          }} />
        </View>
        )}
      </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
});