/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import * as React from 'react';
import AndroidDocumentPicker from 'react-native-android-document-picker';
import { useEffect, useState } from 'react';
import { StyleSheet, View, Text, Image, ScrollView } from 'react-native';

export default function App() {

  const [files, setFiles] = useState(["https://reactjs.org/logo-og.png"]);

  useEffect(() => {
    console.log('files', files);
  }, [files])
  
  return (
    <View style={styles.container}>
      <ScrollView>
      <Text onPress={async () => {
        await AndroidDocumentPicker.openDocument({multipleFiles: false, fileTypes: ["application/pdf"]}, (array) => {
          console.log('array', array);
          setFiles(array);
          setUpdate(!update);
        }, 
        (error) => {
          console.log('error', error);
        });
      }}>Press</Text>

      <View>
        {files.map((file) => 
          <View key={file}>
          <Text>{file}</Text>
          <Image source={{uri: file.fileUri}}
          key={file}
          style={{
            borderColor: 'black',
            borderWidth: 2,
            borderRadius: 5,
            width: 100,
            height: 100,
            margin: 5,
          }} />
        </View>
        )}
      </View>

      <View>
        <Text onPress={() => {
          setFiles(["https://reactjs.org/logo-og.png"]);
        }}>Reset</Text>
      </View>

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
});